CREATE TABLE IF NOT EXISTS notification_preferences (
  user_id INT NOT NULL PRIMARY KEY,
  follow_enabled TINYINT(1) NOT NULL DEFAULT 1,
  review_like_enabled TINYINT(1) NOT NULL DEFAULT 1,
  reply_enabled TINYINT(1) NOT NULL DEFAULT 1,
  moderation_enabled TINYINT(1) NOT NULL DEFAULT 1,
  list_add_enabled TINYINT(1) NOT NULL DEFAULT 1,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
